backend:
  name: git-gateway
  branch: master
media_folder: packages/jingmommy.com/public/upload
public_folder: /upload
collections:
  - name: pages
    label: Pages
    folder: packages/jingmommy.com/src/pages
    extension: mdx
    format: frontmatter
    create: true
    delete: false
    fields:
      - label: Title
        name: title
        widget: string
      - label: Draft
        name: draft
        widget: boolean
      - label: Color
        name: color
        widget: select
        options:
          - red
          - orange
          - amber
          - yellow
          - lime
          - green
          - emerald
          - teal
          - cyan
          - sky
          - blue
          - indigo
          - violet
          - purple
          - fuchsia
          - pink
          - rose
          - slate
          - gray
          - zinc
          - neutral
          - stone
      - label: Body
        name: body
        widget: markdown
  - name: pages > en
    label: Pages > En
    folder: packages/jingmommy.com/src/pages/en
    extension: mdx
    format: frontmatter
    create: true
    delete: false
    fields:
      - label: Title
        name: title
        widget: string
      - label: Draft
        name: draft
        widget: boolean
      - label: Color
        name: color
        widget: select
        options:
          - red
          - orange
          - amber
          - yellow
          - lime
          - green
          - emerald
          - teal
          - cyan
          - sky
          - blue
          - indigo
          - violet
          - purple
          - fuchsia
          - pink
          - rose
          - slate
          - gray
          - zinc
          - neutral
          - stone
      - label: Body
        name: body
        widget: markdown
  - name: pages > zh-tw
    label: Pages > Zh-tw
    folder: packages/jingmommy.com/src/pages/zh-tw
    extension: mdx
    format: frontmatter
    create: true
    delete: false
    fields:
      - label: Title
        name: title
        widget: string
      - label: Draft
        name: draft
        widget: boolean
      - label: Color
        name: color
        widget: select
        options:
          - red
          - orange
          - amber
          - yellow
          - lime
          - green
          - emerald
          - teal
          - cyan
          - sky
          - blue
          - indigo
          - violet
          - purple
          - fuchsia
          - pink
          - rose
          - slate
          - gray
          - zinc
          - neutral
          - stone
      - label: Body
        name: body
        widget: markdown
  - name: pages > zh-tw > about
    label: Pages > Zh-tw > About
    folder: packages/jingmommy.com/src/pages/zh-tw/about
    extension: mdx
    format: frontmatter
    create: true
    delete: false
    fields:
      - label: Title
        name: title
        widget: string
      - label: Draft
        name: draft
        widget: boolean
      - label: Color
        name: color
        widget: select
        options:
          - red
          - orange
          - amber
          - yellow
          - lime
          - green
          - emerald
          - teal
          - cyan
          - sky
          - blue
          - indigo
          - violet
          - purple
          - fuchsia
          - pink
          - rose
          - slate
          - gray
          - zinc
          - neutral
          - stone
      - label: Body
        name: body
        widget: markdown