backend:
  name: git-gateway
  branch: master
media_folder: "packages/jingmommy.com/public/upload" # commit 到 repo 的位置
public_folder: "/upload" # preview 使用 URL path (必須要有傳到網站能看到的 path)
collections:
  # - name: "static-pages"
  #   label: "Static Pages"
  #   files:
  #     - name: "404"
  #       label: "404"
  #       file: "packages/jingmommy.com/src/404.md"
  - name: "pages"
    label: "Pages"
    folder: "packages/jingmommy.com/src/pages"
    extension: "mdx"
    format: "frontmatter"
    create: true
    delete: false
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Draft", name: "draft", widget: "boolean" }
      - label: "Color"
        name: "color"
        widget: "select"
        options:
          - red
          - orange
          - amber
          - yellow
          - lime
          - green
          - emerald
          - teal
          - cyan
          - sky
          - blue
          - indigo
          - violet
          - purple
          - fuchsia
          - pink
          - rose
          - slate
          - gray
          - zinc
          - neutral
          - stone
      - { label: "Body", name: "body", widget: "markdown" }
