env:
  PACKAGE_ID: cms.jingmommy.com
  NETLIFY_SITE_ID: 5fe15505-f825-493f-bd16-85ed5096ba0e
on:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/deploy-cms.jingmommy.com.master.yml'
      - 'packages/cms.jingmommy.com/package.json'
      - 'packages/cms.jingmommy.com/build/**'
      - 'packages/cms.jingmommy.com/public/**'
      - 'packages/cms.jingmommy.com/src/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    outputs:
      PACKAGE_ID: ${{ steps.e.outputs.PACKAGE_ID }}
      result: ${{ steps.netlify-result.outputs.result }}
    steps:
      - id: e
        run: |
          echo "PACKAGE_ID=${{env.PACKAGE_ID}}" >> "$GITHUB_OUTPUT"
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: 'npm'
      - run: |
          npm -w packages/${{env.PACKAGE_ID}} i
          npm -w packages/${{env.PACKAGE_ID}} run build
      # https://github.com/netlify/actions/tree/master/cli
      # https://docs.netlify.com/api-and-cli-guides/cli-guides/get-started-with-cli/#work-with-monorepos
      - uses: netlify/actions/cli@master
        id: deploy
        with:
          args: deploy --filter "packages/${{ env.PACKAGE_ID }}" --prod --dir=public
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
      - id: netlify-result
        run: |
          if [ -z "${{ steps.deploy.outputs.NETLIFY_LIVE_URL }}" ]; then
            echo "result=success" >> $GITHUB_OUTPUT
            echo ${{ steps.deploy.outputs.NETLIFY_LIVE_URL }}
          else
            echo "result=failure" >> $GITHUB_OUTPUT
          fi
  notify:
    if: cancelled() == false
    needs: deploy
    secrets: inherit
    uses: ./.github/workflows/notify.yml
    with:
      conclusion: ${{ needs.deploy.netlify_result }}
      package: ${{ needs.deploy.outputs.PACKAGE_ID }}
